zookeeper:
  image: cherylq/zookeeper:v0
  ports: 
    - "2181:2181"
kafka_0:
  image: cherylq/kafka:v1
  ports:
    - "9092:9092"
  links: 
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 54.172.25.150
    KAFKA_PORT: 9092
    KAFKA_ADVERTISED_PORT: 9092
    KAFKA_BORKER_ID: 0
    KAFKA_LOG_DIRS: "/kafka/kafka-logs-0"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

kafka_1:
  image: cherylq/kafka:v1
  ports:
   - "9093:9093"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 54.172.25.150
    KAFKA_PORT: 9093
    KAFKA_ADVERTISED_PORT: 9093
    KAFKA_BROKER_ID: 1
    KAFKA_LOG_DIRS: "/kafka/kafka-logs-1"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
